// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/ai-engine/v1/ai-engine.proto

package aienginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailType int32

const (
	EmailType_EMAIL_TYPE_UNSPECIFIED      EmailType = 0
	EmailType_EMAIL_TYPE_REJECTION        EmailType = 1
	EmailType_EMAIL_TYPE_INTERVIEW_INVITE EmailType = 2
)

// Enum value maps for EmailType.
var (
	EmailType_name = map[int32]string{
		0: "EMAIL_TYPE_UNSPECIFIED",
		1: "EMAIL_TYPE_REJECTION",
		2: "EMAIL_TYPE_INTERVIEW_INVITE",
	}
	EmailType_value = map[string]int32{
		"EMAIL_TYPE_UNSPECIFIED":      0,
		"EMAIL_TYPE_REJECTION":        1,
		"EMAIL_TYPE_INTERVIEW_INVITE": 2,
	}
)

func (x EmailType) Enum() *EmailType {
	p := new(EmailType)
	*p = x
	return p
}

func (x EmailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ai_engine_v1_ai_engine_proto_enumTypes[0].Descriptor()
}

func (EmailType) Type() protoreflect.EnumType {
	return &file_proto_ai_engine_v1_ai_engine_proto_enumTypes[0]
}

func (x EmailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailType.Descriptor instead.
func (EmailType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{0}
}

type EmailTone int32

const (
	EmailTone_EMAIL_TONE_UNSPECIFIED  EmailTone = 0
	EmailTone_EMAIL_TONE_PROFESSIONAL EmailTone = 1
	EmailTone_EMAIL_TONE_FRIENDLY     EmailTone = 2
	EmailTone_EMAIL_TONE_BRIEF        EmailTone = 3
)

// Enum value maps for EmailTone.
var (
	EmailTone_name = map[int32]string{
		0: "EMAIL_TONE_UNSPECIFIED",
		1: "EMAIL_TONE_PROFESSIONAL",
		2: "EMAIL_TONE_FRIENDLY",
		3: "EMAIL_TONE_BRIEF",
	}
	EmailTone_value = map[string]int32{
		"EMAIL_TONE_UNSPECIFIED":  0,
		"EMAIL_TONE_PROFESSIONAL": 1,
		"EMAIL_TONE_FRIENDLY":     2,
		"EMAIL_TONE_BRIEF":        3,
	}
)

func (x EmailTone) Enum() *EmailTone {
	p := new(EmailTone)
	*p = x
	return p
}

func (x EmailTone) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailTone) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ai_engine_v1_ai_engine_proto_enumTypes[1].Descriptor()
}

func (EmailTone) Type() protoreflect.EnumType {
	return &file_proto_ai_engine_v1_ai_engine_proto_enumTypes[1]
}

func (x EmailTone) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailTone.Descriptor instead.
func (EmailTone) EnumDescriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{1}
}

type GetCandidateScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateScoreRequest) Reset() {
	*x = GetCandidateScoreRequest{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateScoreRequest) ProtoMessage() {}

func (x *GetCandidateScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateScoreRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{0}
}

func (x *GetCandidateScoreRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type ScoreFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Impact        int32                  `protobuf:"varint,3,opt,name=impact,proto3" json:"impact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreFactor) Reset() {
	*x = ScoreFactor{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreFactor) ProtoMessage() {}

func (x *ScoreFactor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreFactor.ProtoReflect.Descriptor instead.
func (*ScoreFactor) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreFactor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScoreFactor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScoreFactor) GetImpact() int32 {
	if x != nil {
		return x.Impact
	}
	return 0
}

type GetCandidateScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchScore    int32                  `protobuf:"varint,1,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	Factors       []*ScoreFactor         `protobuf:"bytes,2,rep,name=factors,proto3" json:"factors,omitempty"`
	HasScore      bool                   `protobuf:"varint,3,opt,name=has_score,json=hasScore,proto3" json:"has_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateScoreResponse) Reset() {
	*x = GetCandidateScoreResponse{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateScoreResponse) ProtoMessage() {}

func (x *GetCandidateScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateScoreResponse.ProtoReflect.Descriptor instead.
func (*GetCandidateScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{2}
}

func (x *GetCandidateScoreResponse) GetMatchScore() int32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *GetCandidateScoreResponse) GetFactors() []*ScoreFactor {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *GetCandidateScoreResponse) GetHasScore() bool {
	if x != nil {
		return x.HasScore
	}
	return false
}

type GetCandidateScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateIds  []string               `protobuf:"bytes,1,rep,name=candidate_ids,json=candidateIds,proto3" json:"candidate_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateScoresRequest) Reset() {
	*x = GetCandidateScoresRequest{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateScoresRequest) ProtoMessage() {}

func (x *GetCandidateScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateScoresRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateScoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandidateScoresRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

type GetCandidateScoresResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key = candidate_id
	Scores        map[string]*GetCandidateScoreResponse `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateScoresResponse) Reset() {
	*x = GetCandidateScoresResponse{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateScoresResponse) ProtoMessage() {}

func (x *GetCandidateScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateScoresResponse.ProtoReflect.Descriptor instead.
func (*GetCandidateScoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{4}
}

func (x *GetCandidateScoresResponse) GetScores() map[string]*GetCandidateScoreResponse {
	if x != nil {
		return x.Scores
	}
	return nil
}

type GenerateCandidateEmailRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CandidateId       string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	GeneratedByUserId string                 `protobuf:"bytes,2,opt,name=generated_by_user_id,json=generatedByUserId,proto3" json:"generated_by_user_id,omitempty"`
	Type              EmailType              `protobuf:"varint,3,opt,name=type,proto3,enum=ai_engine.v1.EmailType" json:"type,omitempty"`
	Tone              EmailTone              `protobuf:"varint,4,opt,name=tone,proto3,enum=ai_engine.v1.EmailTone" json:"tone,omitempty"`
	Locale            string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	RecruiterName     string                 `protobuf:"bytes,6,opt,name=recruiter_name,json=recruiterName,proto3" json:"recruiter_name,omitempty"`
	CompanyName       string                 `protobuf:"bytes,7,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateCandidateEmailRequest) Reset() {
	*x = GenerateCandidateEmailRequest{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCandidateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCandidateEmailRequest) ProtoMessage() {}

func (x *GenerateCandidateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCandidateEmailRequest.ProtoReflect.Descriptor instead.
func (*GenerateCandidateEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateCandidateEmailRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *GenerateCandidateEmailRequest) GetGeneratedByUserId() string {
	if x != nil {
		return x.GeneratedByUserId
	}
	return ""
}

func (x *GenerateCandidateEmailRequest) GetType() EmailType {
	if x != nil {
		return x.Type
	}
	return EmailType_EMAIL_TYPE_UNSPECIFIED
}

func (x *GenerateCandidateEmailRequest) GetTone() EmailTone {
	if x != nil {
		return x.Tone
	}
	return EmailTone_EMAIL_TONE_UNSPECIFIED
}

func (x *GenerateCandidateEmailRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *GenerateCandidateEmailRequest) GetRecruiterName() string {
	if x != nil {
		return x.RecruiterName
	}
	return ""
}

func (x *GenerateCandidateEmailRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type GenerateCandidateEmailResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommunicationId string                 `protobuf:"bytes,1,opt,name=communication_id,json=communicationId,proto3" json:"communication_id,omitempty"`
	Subject         string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body            string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateCandidateEmailResponse) Reset() {
	*x = GenerateCandidateEmailResponse{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCandidateEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCandidateEmailResponse) ProtoMessage() {}

func (x *GenerateCandidateEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCandidateEmailResponse.ProtoReflect.Descriptor instead.
func (*GenerateCandidateEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateCandidateEmailResponse) GetCommunicationId() string {
	if x != nil {
		return x.CommunicationId
	}
	return ""
}

func (x *GenerateCandidateEmailResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GenerateCandidateEmailResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GetCandidateEmailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateEmailsRequest) Reset() {
	*x = GetCandidateEmailsRequest{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateEmailsRequest) ProtoMessage() {}

func (x *GetCandidateEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateEmailsRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateEmailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{7}
}

func (x *GetCandidateEmailsRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

type CommunicationEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CommunicationId   string                 `protobuf:"bytes,1,opt,name=communication_id,json=communicationId,proto3" json:"communication_id,omitempty"`
	Type              EmailType              `protobuf:"varint,2,opt,name=type,proto3,enum=ai_engine.v1.EmailType" json:"type,omitempty"`
	Subject           string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body              string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	GeneratedByUserId string                 `protobuf:"bytes,5,opt,name=generated_by_user_id,json=generatedByUserId,proto3" json:"generated_by_user_id,omitempty"`
	IsSent            bool                   `protobuf:"varint,6,opt,name=is_sent,json=isSent,proto3" json:"is_sent,omitempty"`
	GeneratedAtUnix   int64                  `protobuf:"varint,7,opt,name=generated_at_unix,json=generatedAtUnix,proto3" json:"generated_at_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommunicationEntry) Reset() {
	*x = CommunicationEntry{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunicationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicationEntry) ProtoMessage() {}

func (x *CommunicationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicationEntry.ProtoReflect.Descriptor instead.
func (*CommunicationEntry) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{8}
}

func (x *CommunicationEntry) GetCommunicationId() string {
	if x != nil {
		return x.CommunicationId
	}
	return ""
}

func (x *CommunicationEntry) GetType() EmailType {
	if x != nil {
		return x.Type
	}
	return EmailType_EMAIL_TYPE_UNSPECIFIED
}

func (x *CommunicationEntry) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CommunicationEntry) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CommunicationEntry) GetGeneratedByUserId() string {
	if x != nil {
		return x.GeneratedByUserId
	}
	return ""
}

func (x *CommunicationEntry) GetIsSent() bool {
	if x != nil {
		return x.IsSent
	}
	return false
}

func (x *CommunicationEntry) GetGeneratedAtUnix() int64 {
	if x != nil {
		return x.GeneratedAtUnix
	}
	return 0
}

type GetCandidateEmailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*CommunicationEntry  `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateEmailsResponse) Reset() {
	*x = GetCandidateEmailsResponse{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateEmailsResponse) ProtoMessage() {}

func (x *GetCandidateEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateEmailsResponse.ProtoReflect.Descriptor instead.
func (*GetCandidateEmailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{9}
}

func (x *GetCandidateEmailsResponse) GetEmails() []*CommunicationEntry {
	if x != nil {
		return x.Emails
	}
	return nil
}

type CandidateForComparison struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MatchScore    int32                  `protobuf:"varint,5,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	Skills        []string               `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	ParsedText    string                 `protobuf:"bytes,7,opt,name=parsed_text,json=parsedText,proto3" json:"parsed_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateForComparison) Reset() {
	*x = CandidateForComparison{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateForComparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateForComparison) ProtoMessage() {}

func (x *CandidateForComparison) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateForComparison.ProtoReflect.Descriptor instead.
func (*CandidateForComparison) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{10}
}

func (x *CandidateForComparison) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *CandidateForComparison) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CandidateForComparison) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CandidateForComparison) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CandidateForComparison) GetMatchScore() int32 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *CandidateForComparison) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CandidateForComparison) GetParsedText() string {
	if x != nil {
		return x.ParsedText
	}
	return ""
}

type CompareCandidatesRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Candidates      []*CandidateForComparison `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	JobRequirements string                    `protobuf:"bytes,2,opt,name=job_requirements,json=jobRequirements,proto3" json:"job_requirements,omitempty"`
	Locale          string                    `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompareCandidatesRequest) Reset() {
	*x = CompareCandidatesRequest{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareCandidatesRequest) ProtoMessage() {}

func (x *CompareCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareCandidatesRequest.ProtoReflect.Descriptor instead.
func (*CompareCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{11}
}

func (x *CompareCandidatesRequest) GetCandidates() []*CandidateForComparison {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *CompareCandidatesRequest) GetJobRequirements() string {
	if x != nil {
		return x.JobRequirements
	}
	return ""
}

func (x *CompareCandidatesRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type CandidateComparisonEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experience    string                 `protobuf:"bytes,1,opt,name=experience,proto3" json:"experience,omitempty"`
	Skills        []string               `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	SalaryRange   string                 `protobuf:"bytes,3,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	Risks         string                 `protobuf:"bytes,4,opt,name=risks,proto3" json:"risks,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateComparisonEntry) Reset() {
	*x = CandidateComparisonEntry{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateComparisonEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateComparisonEntry) ProtoMessage() {}

func (x *CandidateComparisonEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateComparisonEntry.ProtoReflect.Descriptor instead.
func (*CandidateComparisonEntry) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{12}
}

func (x *CandidateComparisonEntry) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *CandidateComparisonEntry) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CandidateComparisonEntry) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *CandidateComparisonEntry) GetRisks() string {
	if x != nil {
		return x.Risks
	}
	return ""
}

func (x *CandidateComparisonEntry) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type CompareCandidatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key = candidate_id
	Results       map[string]*CandidateComparisonEntry `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareCandidatesResponse) Reset() {
	*x = CompareCandidatesResponse{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareCandidatesResponse) ProtoMessage() {}

func (x *CompareCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareCandidatesResponse.ProtoReflect.Descriptor instead.
func (*CompareCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{13}
}

func (x *CompareCandidatesResponse) GetResults() map[string]*CandidateComparisonEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type ParseJobDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawText       string                 `protobuf:"bytes,1,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseJobDescriptionRequest) Reset() {
	*x = ParseJobDescriptionRequest{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseJobDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseJobDescriptionRequest) ProtoMessage() {}

func (x *ParseJobDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseJobDescriptionRequest.ProtoReflect.Descriptor instead.
func (*ParseJobDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{14}
}

func (x *ParseJobDescriptionRequest) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *ParseJobDescriptionRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type ParseJobDescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Requirements  []string               `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	WorkFormat    string                 `protobuf:"bytes,4,opt,name=work_format,json=workFormat,proto3" json:"work_format,omitempty"`
	SalaryMin     int32                  `protobuf:"varint,5,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax     int32                  `protobuf:"varint,6,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseJobDescriptionResponse) Reset() {
	*x = ParseJobDescriptionResponse{}
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseJobDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseJobDescriptionResponse) ProtoMessage() {}

func (x *ParseJobDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_engine_v1_ai_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseJobDescriptionResponse.ProtoReflect.Descriptor instead.
func (*ParseJobDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP(), []int{15}
}

func (x *ParseJobDescriptionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ParseJobDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParseJobDescriptionResponse) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *ParseJobDescriptionResponse) GetWorkFormat() string {
	if x != nil {
		return x.WorkFormat
	}
	return ""
}

func (x *ParseJobDescriptionResponse) GetSalaryMin() int32 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *ParseJobDescriptionResponse) GetSalaryMax() int32 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *ParseJobDescriptionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_proto_ai_engine_v1_ai_engine_proto protoreflect.FileDescriptor

const file_proto_ai_engine_v1_ai_engine_proto_rawDesc = "" +
	"\n" +
	"\"proto/ai-engine/v1/ai-engine.proto\x12\fai_engine.v1\"=\n" +
	"\x18GetCandidateScoreRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\"[\n" +
	"\vScoreFactor\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06impact\x18\x03 \x01(\x05R\x06impact\"\x8e\x01\n" +
	"\x19GetCandidateScoreResponse\x12\x1f\n" +
	"\vmatch_score\x18\x01 \x01(\x05R\n" +
	"matchScore\x123\n" +
	"\afactors\x18\x02 \x03(\v2\x19.ai_engine.v1.ScoreFactorR\afactors\x12\x1b\n" +
	"\thas_score\x18\x03 \x01(\bR\bhasScore\"@\n" +
	"\x19GetCandidateScoresRequest\x12#\n" +
	"\rcandidate_ids\x18\x01 \x03(\tR\fcandidateIds\"\xce\x01\n" +
	"\x1aGetCandidateScoresResponse\x12L\n" +
	"\x06scores\x18\x01 \x03(\v24.ai_engine.v1.GetCandidateScoresResponse.ScoresEntryR\x06scores\x1ab\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.ai_engine.v1.GetCandidateScoreResponseR\x05value:\x028\x01\"\xaf\x02\n" +
	"\x1dGenerateCandidateEmailRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12/\n" +
	"\x14generated_by_user_id\x18\x02 \x01(\tR\x11generatedByUserId\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.ai_engine.v1.EmailTypeR\x04type\x12+\n" +
	"\x04tone\x18\x04 \x01(\x0e2\x17.ai_engine.v1.EmailToneR\x04tone\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x12%\n" +
	"\x0erecruiter_name\x18\x06 \x01(\tR\rrecruiterName\x12!\n" +
	"\fcompany_name\x18\a \x01(\tR\vcompanyName\"y\n" +
	"\x1eGenerateCandidateEmailResponse\x12)\n" +
	"\x10communication_id\x18\x01 \x01(\tR\x0fcommunicationId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\">\n" +
	"\x19GetCandidateEmailsRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\"\x90\x02\n" +
	"\x12CommunicationEntry\x12)\n" +
	"\x10communication_id\x18\x01 \x01(\tR\x0fcommunicationId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.ai_engine.v1.EmailTypeR\x04type\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12/\n" +
	"\x14generated_by_user_id\x18\x05 \x01(\tR\x11generatedByUserId\x12\x17\n" +
	"\ais_sent\x18\x06 \x01(\bR\x06isSent\x12*\n" +
	"\x11generated_at_unix\x18\a \x01(\x03R\x0fgeneratedAtUnix\"V\n" +
	"\x1aGetCandidateEmailsResponse\x128\n" +
	"\x06emails\x18\x01 \x03(\v2 .ai_engine.v1.CommunicationEntryR\x06emails\"\xe5\x01\n" +
	"\x16CandidateForComparison\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1f\n" +
	"\vmatch_score\x18\x05 \x01(\x05R\n" +
	"matchScore\x12\x16\n" +
	"\x06skills\x18\x06 \x03(\tR\x06skills\x12\x1f\n" +
	"\vparsed_text\x18\a \x01(\tR\n" +
	"parsedText\"\xa3\x01\n" +
	"\x18CompareCandidatesRequest\x12D\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2$.ai_engine.v1.CandidateForComparisonR\n" +
	"candidates\x12)\n" +
	"\x10job_requirements\x18\x02 \x01(\tR\x0fjobRequirements\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"\xa5\x01\n" +
	"\x18CandidateComparisonEntry\x12\x1e\n" +
	"\n" +
	"experience\x18\x01 \x01(\tR\n" +
	"experience\x12\x16\n" +
	"\x06skills\x18\x02 \x03(\tR\x06skills\x12!\n" +
	"\fsalary_range\x18\x03 \x01(\tR\vsalaryRange\x12\x14\n" +
	"\x05risks\x18\x04 \x01(\tR\x05risks\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\"\xcf\x01\n" +
	"\x19CompareCandidatesResponse\x12N\n" +
	"\aresults\x18\x01 \x03(\v24.ai_engine.v1.CompareCandidatesResponse.ResultsEntryR\aresults\x1ab\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.ai_engine.v1.CandidateComparisonEntryR\x05value:\x028\x01\"O\n" +
	"\x1aParseJobDescriptionRequest\x12\x19\n" +
	"\braw_text\x18\x01 \x01(\tR\arawText\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"\xf4\x01\n" +
	"\x1bParseJobDescriptionResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x03 \x03(\tR\frequirements\x12\x1f\n" +
	"\vwork_format\x18\x04 \x01(\tR\n" +
	"workFormat\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x05 \x01(\x05R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\x06 \x01(\x05R\tsalaryMax\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency*b\n" +
	"\tEmailType\x12\x1a\n" +
	"\x16EMAIL_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EMAIL_TYPE_REJECTION\x10\x01\x12\x1f\n" +
	"\x1bEMAIL_TYPE_INTERVIEW_INVITE\x10\x02*s\n" +
	"\tEmailTone\x12\x1a\n" +
	"\x16EMAIL_TONE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EMAIL_TONE_PROFESSIONAL\x10\x01\x12\x17\n" +
	"\x13EMAIL_TONE_FRIENDLY\x10\x02\x12\x14\n" +
	"\x10EMAIL_TONE_BRIEF\x10\x032\x90\x05\n" +
	"\x0fAIEngineService\x12d\n" +
	"\x11GetCandidateScore\x12&.ai_engine.v1.GetCandidateScoreRequest\x1a'.ai_engine.v1.GetCandidateScoreResponse\x12g\n" +
	"\x12GetCandidateScores\x12'.ai_engine.v1.GetCandidateScoresRequest\x1a(.ai_engine.v1.GetCandidateScoresResponse\x12s\n" +
	"\x16GenerateCandidateEmail\x12+.ai_engine.v1.GenerateCandidateEmailRequest\x1a,.ai_engine.v1.GenerateCandidateEmailResponse\x12g\n" +
	"\x12GetCandidateEmails\x12'.ai_engine.v1.GetCandidateEmailsRequest\x1a(.ai_engine.v1.GetCandidateEmailsResponse\x12d\n" +
	"\x11CompareCandidates\x12&.ai_engine.v1.CompareCandidatesRequest\x1a'.ai_engine.v1.CompareCandidatesResponse\x12j\n" +
	"\x13ParseJobDescription\x12(.ai_engine.v1.ParseJobDescriptionRequest\x1a).ai_engine.v1.ParseJobDescriptionResponseB(Z&internal/proto/ai_engine/v1;aienginev1b\x06proto3"

var (
	file_proto_ai_engine_v1_ai_engine_proto_rawDescOnce sync.Once
	file_proto_ai_engine_v1_ai_engine_proto_rawDescData []byte
)

func file_proto_ai_engine_v1_ai_engine_proto_rawDescGZIP() []byte {
	file_proto_ai_engine_v1_ai_engine_proto_rawDescOnce.Do(func() {
		file_proto_ai_engine_v1_ai_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_engine_v1_ai_engine_proto_rawDesc), len(file_proto_ai_engine_v1_ai_engine_proto_rawDesc)))
	})
	return file_proto_ai_engine_v1_ai_engine_proto_rawDescData
}

var file_proto_ai_engine_v1_ai_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ai_engine_v1_ai_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_ai_engine_v1_ai_engine_proto_goTypes = []any{
	(EmailType)(0),                         // 0: ai_engine.v1.EmailType
	(EmailTone)(0),                         // 1: ai_engine.v1.EmailTone
	(*GetCandidateScoreRequest)(nil),       // 2: ai_engine.v1.GetCandidateScoreRequest
	(*ScoreFactor)(nil),                    // 3: ai_engine.v1.ScoreFactor
	(*GetCandidateScoreResponse)(nil),      // 4: ai_engine.v1.GetCandidateScoreResponse
	(*GetCandidateScoresRequest)(nil),      // 5: ai_engine.v1.GetCandidateScoresRequest
	(*GetCandidateScoresResponse)(nil),     // 6: ai_engine.v1.GetCandidateScoresResponse
	(*GenerateCandidateEmailRequest)(nil),  // 7: ai_engine.v1.GenerateCandidateEmailRequest
	(*GenerateCandidateEmailResponse)(nil), // 8: ai_engine.v1.GenerateCandidateEmailResponse
	(*GetCandidateEmailsRequest)(nil),      // 9: ai_engine.v1.GetCandidateEmailsRequest
	(*CommunicationEntry)(nil),             // 10: ai_engine.v1.CommunicationEntry
	(*GetCandidateEmailsResponse)(nil),     // 11: ai_engine.v1.GetCandidateEmailsResponse
	(*CandidateForComparison)(nil),         // 12: ai_engine.v1.CandidateForComparison
	(*CompareCandidatesRequest)(nil),       // 13: ai_engine.v1.CompareCandidatesRequest
	(*CandidateComparisonEntry)(nil),       // 14: ai_engine.v1.CandidateComparisonEntry
	(*CompareCandidatesResponse)(nil),      // 15: ai_engine.v1.CompareCandidatesResponse
	(*ParseJobDescriptionRequest)(nil),     // 16: ai_engine.v1.ParseJobDescriptionRequest
	(*ParseJobDescriptionResponse)(nil),    // 17: ai_engine.v1.ParseJobDescriptionResponse
	nil,                                    // 18: ai_engine.v1.GetCandidateScoresResponse.ScoresEntry
	nil,                                    // 19: ai_engine.v1.CompareCandidatesResponse.ResultsEntry
}
var file_proto_ai_engine_v1_ai_engine_proto_depIdxs = []int32{
	3,  // 0: ai_engine.v1.GetCandidateScoreResponse.factors:type_name -> ai_engine.v1.ScoreFactor
	18, // 1: ai_engine.v1.GetCandidateScoresResponse.scores:type_name -> ai_engine.v1.GetCandidateScoresResponse.ScoresEntry
	0,  // 2: ai_engine.v1.GenerateCandidateEmailRequest.type:type_name -> ai_engine.v1.EmailType
	1,  // 3: ai_engine.v1.GenerateCandidateEmailRequest.tone:type_name -> ai_engine.v1.EmailTone
	0,  // 4: ai_engine.v1.CommunicationEntry.type:type_name -> ai_engine.v1.EmailType
	10, // 5: ai_engine.v1.GetCandidateEmailsResponse.emails:type_name -> ai_engine.v1.CommunicationEntry
	12, // 6: ai_engine.v1.CompareCandidatesRequest.candidates:type_name -> ai_engine.v1.CandidateForComparison
	19, // 7: ai_engine.v1.CompareCandidatesResponse.results:type_name -> ai_engine.v1.CompareCandidatesResponse.ResultsEntry
	4,  // 8: ai_engine.v1.GetCandidateScoresResponse.ScoresEntry.value:type_name -> ai_engine.v1.GetCandidateScoreResponse
	14, // 9: ai_engine.v1.CompareCandidatesResponse.ResultsEntry.value:type_name -> ai_engine.v1.CandidateComparisonEntry
	2,  // 10: ai_engine.v1.AIEngineService.GetCandidateScore:input_type -> ai_engine.v1.GetCandidateScoreRequest
	5,  // 11: ai_engine.v1.AIEngineService.GetCandidateScores:input_type -> ai_engine.v1.GetCandidateScoresRequest
	7,  // 12: ai_engine.v1.AIEngineService.GenerateCandidateEmail:input_type -> ai_engine.v1.GenerateCandidateEmailRequest
	9,  // 13: ai_engine.v1.AIEngineService.GetCandidateEmails:input_type -> ai_engine.v1.GetCandidateEmailsRequest
	13, // 14: ai_engine.v1.AIEngineService.CompareCandidates:input_type -> ai_engine.v1.CompareCandidatesRequest
	16, // 15: ai_engine.v1.AIEngineService.ParseJobDescription:input_type -> ai_engine.v1.ParseJobDescriptionRequest
	4,  // 16: ai_engine.v1.AIEngineService.GetCandidateScore:output_type -> ai_engine.v1.GetCandidateScoreResponse
	6,  // 17: ai_engine.v1.AIEngineService.GetCandidateScores:output_type -> ai_engine.v1.GetCandidateScoresResponse
	8,  // 18: ai_engine.v1.AIEngineService.GenerateCandidateEmail:output_type -> ai_engine.v1.GenerateCandidateEmailResponse
	11, // 19: ai_engine.v1.AIEngineService.GetCandidateEmails:output_type -> ai_engine.v1.GetCandidateEmailsResponse
	15, // 20: ai_engine.v1.AIEngineService.CompareCandidates:output_type -> ai_engine.v1.CompareCandidatesResponse
	17, // 21: ai_engine.v1.AIEngineService.ParseJobDescription:output_type -> ai_engine.v1.ParseJobDescriptionResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ai_engine_v1_ai_engine_proto_init() }
func file_proto_ai_engine_v1_ai_engine_proto_init() {
	if File_proto_ai_engine_v1_ai_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_engine_v1_ai_engine_proto_rawDesc), len(file_proto_ai_engine_v1_ai_engine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_engine_v1_ai_engine_proto_goTypes,
		DependencyIndexes: file_proto_ai_engine_v1_ai_engine_proto_depIdxs,
		EnumInfos:         file_proto_ai_engine_v1_ai_engine_proto_enumTypes,
		MessageInfos:      file_proto_ai_engine_v1_ai_engine_proto_msgTypes,
	}.Build()
	File_proto_ai_engine_v1_ai_engine_proto = out.File
	file_proto_ai_engine_v1_ai_engine_proto_goTypes = nil
	file_proto_ai_engine_v1_ai_engine_proto_depIdxs = nil
}
