// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/ai-engine/v1/ai-engine.proto

package aienginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIEngineService_GetCandidateScore_FullMethodName      = "/ai_engine.v1.AIEngineService/GetCandidateScore"
	AIEngineService_GenerateCandidateEmail_FullMethodName = "/ai_engine.v1.AIEngineService/GenerateCandidateEmail"
	AIEngineService_GetCandidateEmails_FullMethodName     = "/ai_engine.v1.AIEngineService/GetCandidateEmails"
	AIEngineService_CompareCandidates_FullMethodName      = "/ai_engine.v1.AIEngineService/CompareCandidates"
	AIEngineService_ParseJobDescription_FullMethodName    = "/ai_engine.v1.AIEngineService/ParseJobDescription"
)

// AIEngineServiceClient is the client API for AIEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIEngineServiceClient interface {
	GetCandidateScore(ctx context.Context, in *GetCandidateScoreRequest, opts ...grpc.CallOption) (*GetCandidateScoreResponse, error)
	GenerateCandidateEmail(ctx context.Context, in *GenerateCandidateEmailRequest, opts ...grpc.CallOption) (*GenerateCandidateEmailResponse, error)
	GetCandidateEmails(ctx context.Context, in *GetCandidateEmailsRequest, opts ...grpc.CallOption) (*GetCandidateEmailsResponse, error)
	CompareCandidates(ctx context.Context, in *CompareCandidatesRequest, opts ...grpc.CallOption) (*CompareCandidatesResponse, error)
	ParseJobDescription(ctx context.Context, in *ParseJobDescriptionRequest, opts ...grpc.CallOption) (*ParseJobDescriptionResponse, error)
}

type aIEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIEngineServiceClient(cc grpc.ClientConnInterface) AIEngineServiceClient {
	return &aIEngineServiceClient{cc}
}

func (c *aIEngineServiceClient) GetCandidateScore(ctx context.Context, in *GetCandidateScoreRequest, opts ...grpc.CallOption) (*GetCandidateScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidateScoreResponse)
	err := c.cc.Invoke(ctx, AIEngineService_GetCandidateScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineServiceClient) GenerateCandidateEmail(ctx context.Context, in *GenerateCandidateEmailRequest, opts ...grpc.CallOption) (*GenerateCandidateEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCandidateEmailResponse)
	err := c.cc.Invoke(ctx, AIEngineService_GenerateCandidateEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineServiceClient) GetCandidateEmails(ctx context.Context, in *GetCandidateEmailsRequest, opts ...grpc.CallOption) (*GetCandidateEmailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidateEmailsResponse)
	err := c.cc.Invoke(ctx, AIEngineService_GetCandidateEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineServiceClient) CompareCandidates(ctx context.Context, in *CompareCandidatesRequest, opts ...grpc.CallOption) (*CompareCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareCandidatesResponse)
	err := c.cc.Invoke(ctx, AIEngineService_CompareCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineServiceClient) ParseJobDescription(ctx context.Context, in *ParseJobDescriptionRequest, opts ...grpc.CallOption) (*ParseJobDescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseJobDescriptionResponse)
	err := c.cc.Invoke(ctx, AIEngineService_ParseJobDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIEngineServiceServer is the server API for AIEngineService service.
// All implementations must embed UnimplementedAIEngineServiceServer
// for forward compatibility.
type AIEngineServiceServer interface {
	GetCandidateScore(context.Context, *GetCandidateScoreRequest) (*GetCandidateScoreResponse, error)
	GenerateCandidateEmail(context.Context, *GenerateCandidateEmailRequest) (*GenerateCandidateEmailResponse, error)
	GetCandidateEmails(context.Context, *GetCandidateEmailsRequest) (*GetCandidateEmailsResponse, error)
	CompareCandidates(context.Context, *CompareCandidatesRequest) (*CompareCandidatesResponse, error)
	ParseJobDescription(context.Context, *ParseJobDescriptionRequest) (*ParseJobDescriptionResponse, error)
	mustEmbedUnimplementedAIEngineServiceServer()
}

// UnimplementedAIEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIEngineServiceServer struct{}

func (UnimplementedAIEngineServiceServer) GetCandidateScore(context.Context, *GetCandidateScoreRequest) (*GetCandidateScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidateScore not implemented")
}
func (UnimplementedAIEngineServiceServer) GenerateCandidateEmail(context.Context, *GenerateCandidateEmailRequest) (*GenerateCandidateEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCandidateEmail not implemented")
}
func (UnimplementedAIEngineServiceServer) GetCandidateEmails(context.Context, *GetCandidateEmailsRequest) (*GetCandidateEmailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidateEmails not implemented")
}
func (UnimplementedAIEngineServiceServer) CompareCandidates(context.Context, *CompareCandidatesRequest) (*CompareCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareCandidates not implemented")
}
func (UnimplementedAIEngineServiceServer) ParseJobDescription(context.Context, *ParseJobDescriptionRequest) (*ParseJobDescriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseJobDescription not implemented")
}
func (UnimplementedAIEngineServiceServer) mustEmbedUnimplementedAIEngineServiceServer() {}
func (UnimplementedAIEngineServiceServer) testEmbeddedByValue()                         {}

// UnsafeAIEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIEngineServiceServer will
// result in compilation errors.
type UnsafeAIEngineServiceServer interface {
	mustEmbedUnimplementedAIEngineServiceServer()
}

func RegisterAIEngineServiceServer(s grpc.ServiceRegistrar, srv AIEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedAIEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIEngineService_ServiceDesc, srv)
}

func _AIEngineService_GetCandidateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServiceServer).GetCandidateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngineService_GetCandidateScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServiceServer).GetCandidateScore(ctx, req.(*GetCandidateScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngineService_GenerateCandidateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCandidateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServiceServer).GenerateCandidateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngineService_GenerateCandidateEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServiceServer).GenerateCandidateEmail(ctx, req.(*GenerateCandidateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngineService_GetCandidateEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateEmailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServiceServer).GetCandidateEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngineService_GetCandidateEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServiceServer).GetCandidateEmails(ctx, req.(*GetCandidateEmailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngineService_CompareCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServiceServer).CompareCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngineService_CompareCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServiceServer).CompareCandidates(ctx, req.(*CompareCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngineService_ParseJobDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseJobDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServiceServer).ParseJobDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngineService_ParseJobDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServiceServer).ParseJobDescription(ctx, req.(*ParseJobDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIEngineService_ServiceDesc is the grpc.ServiceDesc for AIEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_engine.v1.AIEngineService",
	HandlerType: (*AIEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCandidateScore",
			Handler:    _AIEngineService_GetCandidateScore_Handler,
		},
		{
			MethodName: "GenerateCandidateEmail",
			Handler:    _AIEngineService_GenerateCandidateEmail_Handler,
		},
		{
			MethodName: "GetCandidateEmails",
			Handler:    _AIEngineService_GetCandidateEmails_Handler,
		},
		{
			MethodName: "CompareCandidates",
			Handler:    _AIEngineService_CompareCandidates_Handler,
		},
		{
			MethodName: "ParseJobDescription",
			Handler:    _AIEngineService_ParseJobDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai-engine/v1/ai-engine.proto",
}
