// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/hiring/v1/hiring.proto

package hiringv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParsingStatus int32

const (
	ParsingStatus_PARSING_STATUS_UNSPECIFIED  ParsingStatus = 0
	ParsingStatus_PARSING_STATUS_SUCCESS      ParsingStatus = 1 // Fully extracted, mandatory fields present
	ParsingStatus_PARSING_STATUS_NEEDS_REVIEW ParsingStatus = 2 // Partially extracted, needs human review
	ParsingStatus_PARSING_STATUS_FAILED       ParsingStatus = 3 // Unreadable file / OCR failed / errors
)

// Enum value maps for ParsingStatus.
var (
	ParsingStatus_name = map[int32]string{
		0: "PARSING_STATUS_UNSPECIFIED",
		1: "PARSING_STATUS_SUCCESS",
		2: "PARSING_STATUS_NEEDS_REVIEW",
		3: "PARSING_STATUS_FAILED",
	}
	ParsingStatus_value = map[string]int32{
		"PARSING_STATUS_UNSPECIFIED":  0,
		"PARSING_STATUS_SUCCESS":      1,
		"PARSING_STATUS_NEEDS_REVIEW": 2,
		"PARSING_STATUS_FAILED":       3,
	}
)

func (x ParsingStatus) Enum() *ParsingStatus {
	p := new(ParsingStatus)
	*p = x
	return p
}

func (x ParsingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParsingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hiring_v1_hiring_proto_enumTypes[0].Descriptor()
}

func (ParsingStatus) Type() protoreflect.EnumType {
	return &file_proto_hiring_v1_hiring_proto_enumTypes[0]
}

func (x ParsingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParsingStatus.Descriptor instead.
func (ParsingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_hiring_v1_hiring_proto_rawDescGZIP(), []int{0}
}

type UpdateCandidateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	ParsingStatus ParsingStatus          `protobuf:"varint,2,opt,name=parsing_status,json=parsingStatus,proto3,enum=hiring.v1.ParsingStatus" json:"parsing_status,omitempty"` // Outcome of the AI parsing
	// Extracted text from PDF
	ParsedText string `protobuf:"bytes,3,opt,name=parsed_text,json=parsedText,proto3" json:"parsed_text,omitempty"`
	// Core fields extracted by LLM
	FirstName string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email     string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	// JSON bytes representing the full extracted profile (skills, exp)
	StructuredData []byte `protobuf:"bytes,7,opt,name=structured_data,json=structuredData,proto3" json:"structured_data,omitempty"`
	// Additional fields extracted by AI
	Location      string   `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Skills        []string `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateProfileRequest) Reset() {
	*x = UpdateCandidateProfileRequest{}
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateProfileRequest) ProtoMessage() {}

func (x *UpdateCandidateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateCandidateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_hiring_v1_hiring_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCandidateProfileRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *UpdateCandidateProfileRequest) GetParsingStatus() ParsingStatus {
	if x != nil {
		return x.ParsingStatus
	}
	return ParsingStatus_PARSING_STATUS_UNSPECIFIED
}

func (x *UpdateCandidateProfileRequest) GetParsedText() string {
	if x != nil {
		return x.ParsedText
	}
	return ""
}

func (x *UpdateCandidateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateCandidateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateCandidateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCandidateProfileRequest) GetStructuredData() []byte {
	if x != nil {
		return x.StructuredData
	}
	return nil
}

func (x *UpdateCandidateProfileRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateCandidateProfileRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

type UpdateCandidateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCandidateProfileResponse) Reset() {
	*x = UpdateCandidateProfileResponse{}
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCandidateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCandidateProfileResponse) ProtoMessage() {}

func (x *UpdateCandidateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCandidateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateCandidateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_hiring_v1_hiring_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCandidateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TransferJobAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobIds        []string               `protobuf:"bytes,2,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferJobAccessRequest) Reset() {
	*x = TransferJobAccessRequest{}
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferJobAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferJobAccessRequest) ProtoMessage() {}

func (x *TransferJobAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferJobAccessRequest.ProtoReflect.Descriptor instead.
func (*TransferJobAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_hiring_v1_hiring_proto_rawDescGZIP(), []int{2}
}

func (x *TransferJobAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransferJobAccessRequest) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

type TransferJobAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferJobAccessResponse) Reset() {
	*x = TransferJobAccessResponse{}
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferJobAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferJobAccessResponse) ProtoMessage() {}

func (x *TransferJobAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hiring_v1_hiring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferJobAccessResponse.ProtoReflect.Descriptor instead.
func (*TransferJobAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_hiring_v1_hiring_proto_rawDescGZIP(), []int{3}
}

func (x *TransferJobAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_hiring_v1_hiring_proto protoreflect.FileDescriptor

const file_proto_hiring_v1_hiring_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/hiring/v1/hiring.proto\x12\thiring.v1\"\xd3\x02\n" +
	"\x1dUpdateCandidateProfileRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12?\n" +
	"\x0eparsing_status\x18\x02 \x01(\x0e2\x18.hiring.v1.ParsingStatusR\rparsingStatus\x12\x1f\n" +
	"\vparsed_text\x18\x03 \x01(\tR\n" +
	"parsedText\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12'\n" +
	"\x0fstructured_data\x18\a \x01(\fR\x0estructuredData\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x16\n" +
	"\x06skills\x18\t \x03(\tR\x06skills\":\n" +
	"\x1eUpdateCandidateProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"L\n" +
	"\x18TransferJobAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ajob_ids\x18\x02 \x03(\tR\x06jobIds\"5\n" +
	"\x19TransferJobAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x87\x01\n" +
	"\rParsingStatus\x12\x1e\n" +
	"\x1aPARSING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PARSING_STATUS_SUCCESS\x10\x01\x12\x1f\n" +
	"\x1bPARSING_STATUS_NEEDS_REVIEW\x10\x02\x12\x19\n" +
	"\x15PARSING_STATUS_FAILED\x10\x032\xde\x01\n" +
	"\rHiringService\x12m\n" +
	"\x16UpdateCandidateProfile\x12(.hiring.v1.UpdateCandidateProfileRequest\x1a).hiring.v1.UpdateCandidateProfileResponse\x12^\n" +
	"\x11TransferJobAccess\x12#.hiring.v1.TransferJobAccessRequest\x1a$.hiring.v1.TransferJobAccessResponseB#Z!internal/proto/hiring/v1;hiringv1b\x06proto3"

var (
	file_proto_hiring_v1_hiring_proto_rawDescOnce sync.Once
	file_proto_hiring_v1_hiring_proto_rawDescData []byte
)

func file_proto_hiring_v1_hiring_proto_rawDescGZIP() []byte {
	file_proto_hiring_v1_hiring_proto_rawDescOnce.Do(func() {
		file_proto_hiring_v1_hiring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hiring_v1_hiring_proto_rawDesc), len(file_proto_hiring_v1_hiring_proto_rawDesc)))
	})
	return file_proto_hiring_v1_hiring_proto_rawDescData
}

var file_proto_hiring_v1_hiring_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hiring_v1_hiring_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_hiring_v1_hiring_proto_goTypes = []any{
	(ParsingStatus)(0),                     // 0: hiring.v1.ParsingStatus
	(*UpdateCandidateProfileRequest)(nil),  // 1: hiring.v1.UpdateCandidateProfileRequest
	(*UpdateCandidateProfileResponse)(nil), // 2: hiring.v1.UpdateCandidateProfileResponse
	(*TransferJobAccessRequest)(nil),       // 3: hiring.v1.TransferJobAccessRequest
	(*TransferJobAccessResponse)(nil),      // 4: hiring.v1.TransferJobAccessResponse
}
var file_proto_hiring_v1_hiring_proto_depIdxs = []int32{
	0, // 0: hiring.v1.UpdateCandidateProfileRequest.parsing_status:type_name -> hiring.v1.ParsingStatus
	1, // 1: hiring.v1.HiringService.UpdateCandidateProfile:input_type -> hiring.v1.UpdateCandidateProfileRequest
	3, // 2: hiring.v1.HiringService.TransferJobAccess:input_type -> hiring.v1.TransferJobAccessRequest
	2, // 3: hiring.v1.HiringService.UpdateCandidateProfile:output_type -> hiring.v1.UpdateCandidateProfileResponse
	4, // 4: hiring.v1.HiringService.TransferJobAccess:output_type -> hiring.v1.TransferJobAccessResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hiring_v1_hiring_proto_init() }
func file_proto_hiring_v1_hiring_proto_init() {
	if File_proto_hiring_v1_hiring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hiring_v1_hiring_proto_rawDesc), len(file_proto_hiring_v1_hiring_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hiring_v1_hiring_proto_goTypes,
		DependencyIndexes: file_proto_hiring_v1_hiring_proto_depIdxs,
		EnumInfos:         file_proto_hiring_v1_hiring_proto_enumTypes,
		MessageInfos:      file_proto_hiring_v1_hiring_proto_msgTypes,
	}.Build()
	File_proto_hiring_v1_hiring_proto = out.File
	file_proto_hiring_v1_hiring_proto_goTypes = nil
	file_proto_hiring_v1_hiring_proto_depIdxs = nil
}
