// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/hiring/v1/hiring.proto

package hiringv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HiringService_UpdateCandidateProfile_FullMethodName = "/hiring.v1.HiringService/UpdateCandidateProfile"
	HiringService_TransferJobAccess_FullMethodName      = "/hiring.v1.HiringService/TransferJobAccess"
)

// HiringServiceClient is the client API for HiringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hiring Service
type HiringServiceClient interface {
	// From AI-Engine service after CVs processing
	UpdateCandidateProfile(ctx context.Context, in *UpdateCandidateProfileRequest, opts ...grpc.CallOption) (*UpdateCandidateProfileResponse, error)
	// From Auth service after user accept invite
	TransferJobAccess(ctx context.Context, in *TransferJobAccessRequest, opts ...grpc.CallOption) (*TransferJobAccessResponse, error)
}

type hiringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHiringServiceClient(cc grpc.ClientConnInterface) HiringServiceClient {
	return &hiringServiceClient{cc}
}

func (c *hiringServiceClient) UpdateCandidateProfile(ctx context.Context, in *UpdateCandidateProfileRequest, opts ...grpc.CallOption) (*UpdateCandidateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCandidateProfileResponse)
	err := c.cc.Invoke(ctx, HiringService_UpdateCandidateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hiringServiceClient) TransferJobAccess(ctx context.Context, in *TransferJobAccessRequest, opts ...grpc.CallOption) (*TransferJobAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferJobAccessResponse)
	err := c.cc.Invoke(ctx, HiringService_TransferJobAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiringServiceServer is the server API for HiringService service.
// All implementations must embed UnimplementedHiringServiceServer
// for forward compatibility.
//
// Hiring Service
type HiringServiceServer interface {
	// From AI-Engine service after CVs processing
	UpdateCandidateProfile(context.Context, *UpdateCandidateProfileRequest) (*UpdateCandidateProfileResponse, error)
	// From Auth service after user accept invite
	TransferJobAccess(context.Context, *TransferJobAccessRequest) (*TransferJobAccessResponse, error)
	mustEmbedUnimplementedHiringServiceServer()
}

// UnimplementedHiringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHiringServiceServer struct{}

func (UnimplementedHiringServiceServer) UpdateCandidateProfile(context.Context, *UpdateCandidateProfileRequest) (*UpdateCandidateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCandidateProfile not implemented")
}
func (UnimplementedHiringServiceServer) TransferJobAccess(context.Context, *TransferJobAccessRequest) (*TransferJobAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferJobAccess not implemented")
}
func (UnimplementedHiringServiceServer) mustEmbedUnimplementedHiringServiceServer() {}
func (UnimplementedHiringServiceServer) testEmbeddedByValue()                       {}

// UnsafeHiringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HiringServiceServer will
// result in compilation errors.
type UnsafeHiringServiceServer interface {
	mustEmbedUnimplementedHiringServiceServer()
}

func RegisterHiringServiceServer(s grpc.ServiceRegistrar, srv HiringServiceServer) {
	// If the following call panics, it indicates UnimplementedHiringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HiringService_ServiceDesc, srv)
}

func _HiringService_UpdateCandidateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCandidateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiringServiceServer).UpdateCandidateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HiringService_UpdateCandidateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiringServiceServer).UpdateCandidateProfile(ctx, req.(*UpdateCandidateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HiringService_TransferJobAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferJobAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiringServiceServer).TransferJobAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HiringService_TransferJobAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiringServiceServer).TransferJobAccess(ctx, req.(*TransferJobAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HiringService_ServiceDesc is the grpc.ServiceDesc for HiringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HiringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hiring.v1.HiringService",
	HandlerType: (*HiringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCandidateProfile",
			Handler:    _HiringService_UpdateCandidateProfile_Handler,
		},
		{
			MethodName: "TransferJobAccess",
			Handler:    _HiringService_TransferJobAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hiring/v1/hiring.proto",
}
