package audit

// Action codes for audit logging.
// Each service seeds its own codes on startup via SeedActionTypes().

// Auth service actions
const (
	AuthOwnerRegistered = "auth.owner_registered"
	AuthInviteSent      = "auth.invite_sent"
	AuthInviteAccepted  = "auth.invite_accepted"
	AuthUserLoggedIn    = "auth.user_logged_in"
	AuthUserLoggedOut   = "auth.user_logged_out"
)

// Hiring service actions
const (
	HiringJobCreated       = "hiring.job_created"
	HiringJobPublished     = "hiring.job_published"
	HiringJobClosed        = "hiring.job_closed"
	HiringJobArchived      = "hiring.job_archived"
	HiringJobDeleted       = "hiring.job_deleted"
	HiringCandidateAdded   = "hiring.candidate_added"
	HiringCandidateMoved   = "hiring.candidate_moved"
	HiringCandidateDeleted = "hiring.candidate_deleted"
	HiringAccessGranted    = "hiring.access_granted"
	HiringAccessRevoked    = "hiring.access_revoked"
	HiringStageCreated     = "hiring.stage_created"
	HiringStageUpdated     = "hiring.stage_updated"
	HiringStageDeleted     = "hiring.stage_deleted"
)

// AI Engine service actions
const (
	AIResumeParsed   = "ai.resume_parsed"
	AIScoreComputed  = "ai.score_computed"
	AIEmailGenerated = "ai.email_generated"
)

// actionDefinition represents a single action code and its description.
type actionDefinition struct {
	Service     string
	Code        string
	Description string
}

// AllActions returns the complete list of known action definitions.
// Used by SeedActionTypes() to upsert into logging.t_action_types.
func AllActions() []actionDefinition {
	return []actionDefinition{
		// Auth
		{Service: "auth", Code: AuthOwnerRegistered, Description: "Owner registered a new team"},
		{Service: "auth", Code: AuthInviteSent, Description: "Invite sent to a user"},
		{Service: "auth", Code: AuthInviteAccepted, Description: "User accepted an invite"},
		{Service: "auth", Code: AuthUserLoggedIn, Description: "User logged in"},
		{Service: "auth", Code: AuthUserLoggedOut, Description: "User logged out"},

		// Hiring
		{Service: "hiring", Code: HiringJobCreated, Description: "Job vacancy created"},
		{Service: "hiring", Code: HiringJobPublished, Description: "Job vacancy published"},
		{Service: "hiring", Code: HiringJobClosed, Description: "Job vacancy closed"},
		{Service: "hiring", Code: HiringJobArchived, Description: "Job vacancy archived"},
		{Service: "hiring", Code: HiringJobDeleted, Description: "Job vacancy deleted"},
		{Service: "hiring", Code: HiringCandidateAdded, Description: "Candidate added to a job"},
		{Service: "hiring", Code: HiringCandidateMoved, Description: "Candidate moved between pipeline stages"},
		{Service: "hiring", Code: HiringCandidateDeleted, Description: "Candidate deleted"},
		{Service: "hiring", Code: HiringAccessGranted, Description: "User granted access to a job"},
		{Service: "hiring", Code: HiringAccessRevoked, Description: "User access to a job revoked"},
		{Service: "hiring", Code: HiringStageCreated, Description: "Pipeline stage created"},
		{Service: "hiring", Code: HiringStageUpdated, Description: "Pipeline stage updated"},
		{Service: "hiring", Code: HiringStageDeleted, Description: "Pipeline stage deleted"},

		// AI Engine
		{Service: "ai_engine", Code: AIResumeParsed, Description: "Resume parsing completed"},
		{Service: "ai_engine", Code: AIScoreComputed, Description: "Candidate scoring completed"},
		{Service: "ai_engine", Code: AIEmailGenerated, Description: "Email generated by AI"},
	}
}
